-- Generated by scripts/palette.py -- run `python3 scripts/palette.py --write`
-- to re-derive. Don't hand-edit; edit the generator.
--
-- Seeds: https://colorhunt.co/palette/1801614f1787eb3678fb773c
-- #180161 #4F1787 #EB3678 #FB773C -- all violet and warm. No green, teal, cyan
-- or blue exists in that set, so those are derived in OKLCH at a lightness band
-- matched to the seeds, which keeps diff and diagnostics readable without
-- reading as a second palette bolted on.
--
-- The numeric suffixes are tokyonight's naming and are NOT a lightness ordering:
-- blue1/blue5/blue6/green1 are bright foregrounds, blue7/red1 are dark surfaces.

---@class Palette
local M = {
  bg = "#16013e",         -- seed #180161, darkened
  bg_dark = "#0f0033",
  bg_dark1 = "#080026",
  bg_highlight = "#210f50",
  fg = "#deddf6",
  fg_dark = "#bfbdda",
  fg_gutter = "#2f265a",
  comment = "#696595",
  dark3 = "#514b7c",
  dark5 = "#7873a5",
  terminal_black = "#413a6d",

  pink = "#EB3678",       -- seed, verbatim
  orange = "#FB773C",     -- seed, verbatim

  red = "#ef546c",
  yellow = "#e3ae28",
  green = "#68cc7a",
  teal = "#42c2ad",
  cyan = "#58cce7",
  blue = "#739bf5",
  purple = "#a87eeb",
  magenta = "#dd7bd5",

  blue1 = "#52cff3",      -- bright: Type, Special, accent icons
  blue5 = "#8edefe",      -- bright: operators
  blue6 = "#aaf0f4",      -- bright: regex
  green1 = "#72d8b3",     -- bright: @property, @variable.member

  blue7 = "#303e72",
  red1 = "#cc3143",
  green2 = "#42a68f",
  magenta2 = "#df2187",

  -- the two dark seeds, verbatim, as raised surfaces (visual, search, borders)
  seed_indigo = "#180161",
  seed_purple = "#4F1787",

  -- diff surfaces, set directly rather than blended: see build()
  diff_add = "#07411c",
  diff_change = "#1b345e",
  diff_delete = "#601623",
  diff_text = "#2d4f86",

  git = {
    add = "#348757",
    change = "#4a76ae",
    delete = "#a54358",
  },
}

return M
