-- Generated by scripts/palette.py -- run `python3 scripts/palette.py --write`
-- to regenerate. Don't hand-edit; edit the generator.
--
-- ayu dark, from https://github.com/ayu-theme/ayu-colors (themes/dark.yaml).
-- The ayu values are verbatim; the rest are derived to fill keys the highlight
-- groups need and ayu has no equivalent for.
--
-- One deliberate departure: ayu's keyword orange and constant purple are
-- swapped. Six of ayu's eleven accents sit inside a 63-degree warm band, with
-- keyword only 6 degrees from operator and 18 from func. Keywords are the most
-- frequent token, so that band ends up dominating the screen. Purple sits 69
-- degrees clear of anything else; constants are rare enough that the orange
-- stays pleasant there. The key names below are the ayu hex they came from.

---@class Palette
local M = {
  bg = "#10141C",           -- ayu surface.lift -- editor
  bg_dark = "#0D1017",      -- ayu surface.base -- sidebars, floats, statusline
  bg_dark1 = "#0F131A",
  bg_highlight = "#161A24",
  fg = "#BFBDB6",
  fg_dark = "#a3a19a",
  fg_gutter = "#1B1F29",
  comment = "#5A6378",
  dark3 = "#3f475b",
  dark5 = "#778096",
  terminal_black = "#353d50",

  orange = "#FF8F40",       -- ayu keyword hex -- used here for constants, see below
  yellow = "#FFB454",       -- ayu func
  blue = "#59C2FF",         -- ayu entity
  green = "#AAD94C",        -- ayu string
  teal = "#95E6CB",         -- ayu regexp
  red = "#F07178",          -- ayu markup
  purple = "#D2A6FF",       -- ayu constant hex -- used here for keywords
  magenta = "#F29668",      -- ayu operator
  cyan = "#39BAE6",         -- ayu tag
  peach = "#E6C08A",        -- ayu special
  accent = "#E6B450",       -- ayu accent

  blue1 = "#39BAE6",        -- bright: Type, Special, accent icons
  blue5 = "#8fd3ff",
  blue6 = "#a5f7db",
  green1 = "#95E6CB",       -- bright: @property, @variable.member
  blue7 = "#004161",        -- dark surface
  red1 = "#D95757",
  green2 = "#709701",
  magenta2 = "#a67bd0",

  bg_visual = "#193155",
  bg_search = "#4C4126",
  error = "#D95757",

  diff_add = "#183b0b",
  diff_change = "#05335b",
  diff_delete = "#551b21",
  diff_text = "#1c4a76",

  git = {
    add = "#70BF56",
    change = "#73B8FF",
    delete = "#F26D78",
  },
}

return M
