-- Generated by scripts/palette.py -- run `python3 scripts/palette.py --write`
-- to regenerate. Don't hand-edit; edit the generator.
--
-- JetBrains Dark, from the IntelliJ snapshot in
-- https://github.com/nickkadutskyi/jb.nvim (lua/jb/intellij-palette.json).
--
-- JetBrains leaves types, operators and calls in the default text color, which
-- a palette can't say. `blue` and `magenta` carry UI hues here, and
-- lua/implicitly/groups/jb.lua turns the syntax back to plain text. The inline
-- notes below are the ayu names the keys were laid out for; see the role table
-- in scripts/palette.py.

---@class Palette
local M = {
  bg = "#191A1C",           -- ayu surface.lift -- editor
  bg_dark = "#131416",      -- ayu surface.base -- sidebars, floats, statusline
  bg_dark1 = "#131416",
  bg_highlight = "#1F2024",
  fg = "#BCBEC4",
  fg_dark = "#A1A3AB",
  fg_gutter = "#393B40",
  comment = "#7A7E85",
  dark3 = "#4B5059",
  dark5 = "#868A91",
  terminal_black = "#6F737A",

  orange = "#C77DBB",       -- ayu keyword hex -- used here for constants, see below
  yellow = "#56A8F5",       -- ayu func
  blue = "#548AF7",         -- ayu entity
  green = "#6AAB73",        -- ayu string
  teal = "#16BAAC",         -- ayu regexp
  red = "#F75464",          -- ayu markup
  purple = "#CF8E6D",       -- ayu constant hex -- used here for keywords
  magenta = "#B189F5",      -- ayu operator
  cyan = "#2AACB8",         -- ayu tag
  peach = "#B3AE60",        -- ayu special
  accent = "#F2C55C",       -- ayu accent

  blue1 = "#6089EF",        -- bright: Type, Special, accent icons
  blue5 = "#6e9fff",
  blue6 = "#36cabc",
  green1 = "#83c58b",       -- bright: @property, @variable.member
  blue7 = "#25324D",        -- dark surface
  red1 = "#FA6675",
  green2 = "#5F826B",
  magenta2 = "#875ec6",

  bg_visual = "#214283",
  bg_search = "#114957",
  error = "#F75464",

  diff_add = "#294436",
  diff_change = "#25324D",
  diff_delete = "#450505",
  diff_text = "#385570",
  border_highlight = "#393B40",

  git = {
    add = "#549159",
    change = "#375FAD",
    delete = "#868A91",
  },
}

return M
