-- Generated by scripts/palette.py -- run `python3 scripts/palette.py --write`
-- to regenerate. Don't hand-edit; edit the generator.
--
-- Green on black, the look of a phosphor CRT terminal. Four values are taken
-- literally from hackertyper.net's stylesheet -- #000000 background, #00FF00
-- text, #3df7f7 cyan, #ff0000 red -- and the rest of the ramp is generated
-- around them at the same hue so the screen reads as one phosphor.
--
-- The key names are hue names and they lie here: `purple` is the bright green
-- that colors keywords, `orange` is the lime on constants. See the role table
-- in scripts/palette.py.

---@class Palette
local M = {
  bg = "#000200",           -- ayu surface.lift -- editor
  bg_dark = "#000000",      -- ayu surface.base -- sidebars, floats, statusline
  bg_dark1 = "#000000",
  bg_highlight = "#051c07",
  fg = "#7bd77f",
  fg_dark = "#6cb26f",
  fg_gutter = "#112e13",
  comment = "#3a6b3d",
  dark3 = "#244d26",
  dark5 = "#569158",
  terminal_black = "#1b3f1d",

  orange = "#f6c330",       -- ayu keyword hex -- used here for constants, see below
  yellow = "#cae758",       -- ayu func
  blue = "#3df7f7",         -- ayu entity
  green = "#abf3ad",        -- ayu string
  teal = "#62bc9c",         -- ayu regexp
  red = "#ef6661",          -- ayu markup
  purple = "#00FF00",       -- ayu constant hex -- used here for keywords
  magenta = "#44d6d6",      -- ayu operator
  cyan = "#87e4fe",         -- ayu tag
  peach = "#cff8cf",        -- ayu special
  accent = "#f4a437",       -- ayu accent

  blue1 = "#3df7f7",        -- bright: Type, Special, accent icons
  blue5 = "#8cebea",
  blue6 = "#b5f8ea",
  green1 = "#99e89b",       -- bright: @property, @variable.member
  blue7 = "#003e41",        -- dark surface
  red1 = "#ff0000",
  green2 = "#59985b",
  magenta2 = "#0cb6a8",

  bg_visual = "#052a09",
  bg_search = "#353600",
  error = "#ff0000",

  diff_add = "#042d09",
  diff_change = "#002b2d",
  diff_delete = "#411110",
  diff_text = "#00474a",

  git = {
    add = "#5bbe62",
    change = "#3ebfc6",
    delete = "#e9504d",
  },
}

return M
